### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by seunzu** [hk-plantify/cash-service#3]
- [x]  초기세팅
    - [x]  `Jasypt`
    - [x]  `WebConfig`
    - [x] `global exception`
- [x] 서비스
    - [x] cash service
    - [x] [API 명세서](https://www.notion.so/0123suh/Plantify-dd4ed7aaca484705bc615fd61ab90128?p=10e86c5edd3f80edb3ffdffd5a4333e8&pm=s)
- [x]  테스트
    - [x] `Swagger`

**Comment by choihoyoon** [comment]
@seunzu 
서비스 로직안에서 계속 도메인을 수정하는데 서비스에서 할 작업이 아님 도메인에서 해야함
